---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.4.1
  privileged: true
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: docker-publish-master
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: cnrancher/octopus-api-server
    tag: "${DRONE_BRANCH}-amd64"
    username:
      from_secret: docker_username
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
      - "refs/tags/v*"
    event:
      include:
      - push

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: cnrancher/octopus-api-server
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
      - "refs/tags/v*"
    event:
      include:
      - tag

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
      - "refs/tags/v*"
    event:
      include:
      - tag

node:
  instance: agent-amd64
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
trigger:
  event:
    include:
    - push
    - pull_request
    - tag

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: docker-publish-master
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: cnrancher/octopus-api-server
    tag: "${DRONE_BRANCH}-arm64"
    username:
      from_secret: docker_username
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
      - "refs/tags/v*"
    event:
      include:
      - push

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: cnrancher/octopus-api-server
    tag: "${DRONE_TAG}-arm64"
    username:
      from_secret: docker_username
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
      - "refs/tags/v*"
    event:
      include:
      - tag

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
      - "refs/tags/v*"
    event:
      include:
      - tag

node:
  instance: agent-arm64
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
trigger:
  event:
    include:
    - push
    - pull_request
    - tag

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: docker-publish-master
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: cnrancher/octopus-api-server
    tag: "${DRONE_BRANCH}-arm"
    username:
      from_secret: docker_username
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
      - "refs/tags/v*"
    event:
      include:
      - push

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: cnrancher/octopus-api-server
    tag: "${DRONE_TAG}-arm"
    username:
      from_secret: docker_username
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
      - "refs/tags/v*"
    event:
      include:
      - tag

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
      - "refs/tags/v*"
    event:
      include:
      - tag

node:
  instance: agent-arm
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
trigger:
  event:
    include:
    - push
    - pull_request
    - tag

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    - linux/arm
    target: "cnrancher/octopus-api-server:${DRONE_BRANCH}"
    template: "cnrancher/octopus-api-server:${DRONE_BRANCH}-ARCH"
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
      - "refs/tags/v*"
    event:
      include:
      - push

node:
  instance: agent-amd64
trigger:
  event:
    include:
    - push
    - pull_request
    - tag
depends_on:
- amd64
- arm64
- arm
